# /etc/supervisor/conf.d/supervisord.conf
[program:casper-node-launcher]
user=jh
command=/usr/bin/casper-node-launcher
# environment=CASPER_CONFIG_DIR="/home/jh/mynetwork-node/etc",CASPER_BIN_DIR="/home/jh/mynetwork-node/bin",RUST_LOG="debug"
environment=CASPER_CONFIG_DIR="/home/jh/mynetwork-node/etc",CASPER_BIN_DIR="/home/jh/mynetwork-node/bin"
autostart=true
autorestart=true
startsecs=6
startretries=20
stdout_logfile=/home/jh/mynetwork-node/logs/casper-node.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile=/home/jh/mynetwork-node/logs/casper-node.err
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5