#!/bin/bash
set -e

NETWORK_CONF_URL="http://mynetwork.local:5000/mynetwork/mynetwork.conf"
NETWORK_CONF_PATH="/etc/casper/network_configs/mynetwork.conf"

# Download network config
echo "Downloading network config..."
mkdir -p /etc/casper/network_configs
curl -fLo "$NETWORK_CONF_PATH" "$NETWORK_CONF_URL"

# Copy pre-generated validator keys for this pod's ordinal (myapp-0 → 0, etc.)
ORDINAL="${HOSTNAME##*-}"
KEY_SRC="/validator-keys/${ORDINAL}"
if [ ! -d "$KEY_SRC" ]; then
  echo "ERROR: Validator key mount not found at ${KEY_SRC}"
  exit 1
fi
mkdir -p /etc/casper/validator_keys
cp "${KEY_SRC}/secret_key.pem" /etc/casper/validator_keys/
cp "${KEY_SRC}/public_key.pem" /etc/casper/validator_keys/
cp "${KEY_SRC}/public_key_hex" /etc/casper/validator_keys/
echo "Copied validator keys for ordinal ${ORDINAL}."

# Ensure casper-node process can read validator keys.
chown -R casper:casper /etc/casper/validator_keys
chmod 700 /etc/casper/validator_keys
chmod 600 /etc/casper/validator_keys/secret_key.pem
if [ -f /etc/casper/validator_keys/public_key_hex ]; then
  chmod 644 /etc/casper/validator_keys/public_key_hex
fi
# Stage protocols (downloads bin.tar.gz and config.tar.gz for each version)
echo "Staging protocols..."
su -s /bin/bash casper -c "casper-node-util stage_protocols mynetwork.conf"

# detect latest protocol version
LATEST_VERSION=$(ls -d /etc/casper/[0-9]*_*/ 2>/dev/null | sort -V | tail -1 | xargs basename)
if [ -z "$LATEST_VERSION" ]; then
  echo "ERROR: No protocol version dirs found under /etc/casper/"
  exit 1
fi
echo "Latest protocol version: $LATEST_VERSION"

# set trusted_hash (unless INITIAL_VERSION is TRUE)
if [ "$INITIAL_VERSION" = "TRUE" ] || [ "$INITIAL_VERSION" = "true" ]; then
  echo "INITIAL_VERSION is true. Skipping trusted_hash update."
else
  echo "INITIAL_VERSION is not true (or unset). Setting trusted_hash..."
  TRUSTED_HASH=$(casper-client get-block --node-address http://192.168.2.101:7777 | jq -r .result.block_with_signatures.block.Version2.hash)
  if [ -z "$TRUSTED_HASH" ] || [ "$TRUSTED_HASH" = "null" ]; then
    echo "ERROR: Failed to get trusted_hash from node"
    exit 1
  fi
  sed -i "s/^#\?trusted_hash = .*/trusted_hash = '${TRUSTED_HASH}'/" /etc/casper/${LATEST_VERSION}/config.toml
fi

# Optionally source peer discovery output generated by the initContainer.
if [ -f /peer/peers.env ]; then
  # shellcheck disable=SC1091
  . /peer/peers.env
  echo "Loaded /peer/peers.env"
fi


CONFIG_PATH="/etc/casper/${LATEST_VERSION}/config.toml"

# Set the node's public gossip address.
sed -i "s/^public_address = .*/public_address = '${OWN_IP}:0'/" "$CONFIG_PATH"

# Build known_addresses from discovered peers.
PEER_LIST=""
for i in 0 1 2; do
  VAR="PEER_${i}_IP"
  PEER_IP="${!VAR:-}"
  if [ -n "$PEER_IP" ]; then
    if [ -n "$PEER_LIST" ]; then
      PEER_LIST="$PEER_LIST, "
    fi
    PEER_LIST="$PEER_LIST'${PEER_IP}:35000'"
  fi
done

if [ -n "$PEER_LIST" ]; then
  sed -i "s/^known_addresses = .*/known_addresses = [${PEER_LIST}]/" "$CONFIG_PATH"
  echo "Updated known_addresses from discovered peers: [${PEER_LIST}]"
else
  echo "No discovered peer IPs found; leaving known_addresses unchanged."
fi

# Run logrotate hourly in the background
while true; do logrotate /etc/logrotate.d/casper; sleep 3600; done &

# Run casper-node-launcher in the foreground as PID 1
echo "Starting casper-node-launcher as user casper..."
export RUST_LOG="${RUST_LOG:-info}"
mkdir -p /var/log/casper
chown -R casper:casper /var/log/casper

# Drop privileges to "casper" user and keep logs on container stdout/stderr
exec su -s /bin/bash casper -c "export RUST_LOG='${RUST_LOG}'; exec /usr/bin/casper-node-launcher"
